export const actionPriceColumnDefault = [
    { field: 'MSRP' },
    { field: 'WholesalePriceLocal' },
    { field: 'CurrentLCSellingPrice' },
    { field: 'TotalDiscount' },
    { field: 'LastMDDate' },
    { field: 'MDCount' },
    { field: 'MarkUp' },
    { field: 'ContributionMargin' },
    { field: 'PriceElasticitySC' },
    { field: 'PriceElasticityConfidence' },
    { field: 'RecommendedMarkPCTElasticity' },
    { field: 'RecommendedMarkPRCElasticity' },
    { field: 'TotalDiscountAfterMarkElasticity' },
    { field: 'RecommendedMarkPCTInterval' },
    { field: 'RecommendedMarkPRCInterval' },
    { field: 'TotalDiscountAfterMarkInterval' },
];

export const actionPriceColumnEachSea = [
    { field: 'MSRP' },
    { field: 'MSRPUSD', headerName: 'MSRP USD' },
    { field: 'WholesalePriceLocal' },
    { field: 'CurrentLCSellingPrice' },
    { field: 'TotalDiscount' },
    { field: 'LastMDDate' },
    { field: 'MDCount' },
    { field: 'MarkUp' },
    { field: 'ContributionMargin' },
    { field: 'PriceElasticitySC' },
    { field: 'PriceElasticityConfidence' },
    { field: 'RecommendedMarkPCTElasticity' },
    { field: 'RecommendedMarkPRCElasticity' },
    { field: 'TotalDiscountAfterMarkElasticity' },
    { field: 'RecommendedMarkPCTInterval' },
    { field: 'RecommendedMarkPRCInterval' },
    { field: 'TotalDiscountAfterMarkInterval' },
];

export const actionPriceColumnSouthEastAsia = [
    { field: 'MSRPUSD', headerName: 'MSRP USD' },
    { field: 'WholesalePriceUSD' },
    { field: 'CurrentUSDSellingPrice' },
    { field: 'TotalDiscount' },
    { field: 'LastMDDate' },
    { field: 'MDCount' },
    { field: 'MarkUp' },
    { field: 'ContributionMargin' },
    { field: 'PriceElasticitySC' },
    { field: 'PriceElasticityConfidence' },
    { field: 'RecommendedMarkPCTElasticity' },
    { field: 'RecommendedMarkPRCElasticity' },
    { field: 'TotalDiscountAfterMarkElasticity' },
    { field: 'RecommendedMarkPCTInterval' },
    { field: 'RecommendedMarkPRCInterval' },
    { field: 'TotalDiscountAfterMarkInterval' },
];