// import React, { useContext } from 'react';
// import { SelectedChannelContext } from '../../../context/rowDetailsContext';

export const actionInventoryColumnJapan = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1083_Contracts', headerName: '1083 Contracts' },
    { field: '1084_Contracts', headerName: '1084 Contracts' },
    { field: '1085_Contracts', headerName: '1085 Contracts' },
    //{ field: selectedChannel === 'NDDC' ? 'NSO_Contracts' : selectedChannel === 'NSO' ? 'NDDC_Contracts' : null },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1083', headerName: "GA 1083" },
    { field: 'GA_1084', headerName: "GA 1084" },
    { field: 'GA_1085', headerName: "GA 1085" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsZOZOInventory', headerName: "DOMs ZOZO Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnMexico = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1098_Contracts', headerName: '1098 Contracts' },
    //{ field: selectedChannel === 'NDDC' ? 'NSO_Contracts' : null },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1098', headerName: "GA 1098" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnIndonesia = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: '1034_Contracts', headerName: '1034 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'GA_1034', headerName: "GA 1034" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnMalaysia = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: '1036_Contracts', headerName: '1036 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'GA_1036', headerName: "GA 1036" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnPhilippines = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: '1037_Contracts', headerName: '1037 Contracts' },
    { field: '1041_Contracts', headerName: '1041 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'GA_1037', headerName: "GA 1037" },
    { field: 'GA_1041', headerName: "GA 1041" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnIndia = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: '1089_Contracts', headerName: '1089 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'GA_1089', headerName: "GA 1089" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnThailand = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: '1038_Contracts', headerName: '1038 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'GA_1038', headerName: "GA 1038" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnSingapore = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: '1035_Contracts', headerName: '1035 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'GA_1035', headerName: "GA 1035" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];

export const actionInventoryColumnVietnam = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
]

export const actionInventoryColumnSouthEastAsia = [
    { field: 'Contracts' },
    { field: 'UnassignedZerotoThirtyDaysOut', headerName: 'Unassigned Qty 0_30' },
    { field: 'UnassignedThirtyonetoSixtyDaysOut', headerName: 'Unassigned Qty 31_60' },
    { field: 'UnassignedSixtyonePlusDaysOut', headerName: 'Unassigned Qty 61 Plus' },
    { field: '1024_Contracts', headerName: '1024 Contracts' },
    { field: '1034_Contracts', headerName: '1034 Contracts' },
    { field: '1035_Contracts', headerName: '1035 Contracts' },
    { field: '1036_Contracts', headerName: '1036 Contracts' },
    { field: '1037_Contracts', headerName: '1037 Contracts' },
    { field: '1038_Contracts', headerName: '1038 Contracts' },
    { field: '1041_Contracts', headerName: '1041 Contracts' },
    { field: '1089_Contracts', headerName: '1089 Contracts' },
    { field: 'NSO_Contracts' },
    { field: 'WholesaleContract' },
    { field: 'StoreIOH' },
    { field: 'InTransit' },
    { field: 'OnOrder' },
    { field: 'GA_1024', headerName: "GA 1024" },
    { field: 'GA_1034', headerName: "GA 1034" },
    { field: 'GA_1035', headerName: "GA 1035" },
    { field: 'GA_1036', headerName: "GA 1036" },
    { field: 'GA_1037', headerName: "GA 1037" },
    { field: 'GA_1038', headerName: "GA 1038" },
    { field: 'GA_1041', headerName: "GA 1041" },
    { field: 'GA_1089', headerName: "GA 1089" },
    { field: 'DOMsInventory', headerName: "DOMs Inventory" },
    { field: 'DOMsNDDCInventory', headerName: "DOMs NDDC Inventory" },
    { field: 'DOMsNSOInventory', headerName: "DOMs NSO Inventory" },
    { field: 'DOMsNFSInventory', headerName: "DOMs NFS Inventory" },
    { field: 'DOMsEMPInventory', headerName: "DOMs EMP Inventory" },
    { field: 'DOMsGAInventory', headerName: "DOMs GA Inventory" },
    { field: 'DOMsLAZADAInventory', headerName: "DOMs LAZADA Inventory" },
    { field: 'SizeCountOwned' },
    { field: 'SizeCountTotal' },
    { field: 'SizeIntegrity' },
    { field: 'ChannelWOH' },
    { field: 'MarketPlaceWOH' },
    { field: 'RecommendedChaseUnits' },
    { field: 'RecommendedCancelUnits' }
];