export const actionSalesColumnCommon = [
    { field: 'NetUnitsLastWeek' },
    { field: 'NetUnitsFourWkAvg', headerName: 'Net Units 4W Avg' },
    { field: 'NetUnitsFourWkRolling', headerName: 'Net Units 4W rolling' },
    { field: 'NetUnitsThirteenWkAvg', headerName: 'Net Units 13W Avg' },
    { field: 'NetUnitsMTD' },
    { field: 'NetUnitsSTD' },
    { field: 'NetSalesLW' },
    { field: 'NetSalesFourWkAvg', headerName: 'Net Sales 4w avg' },
    { field: 'NetSalesFourWkRolling', headerName: 'Net Sales 4w rolling' },
    { field: 'NetSalesMTD' },
    { field: 'NetSalesSTD' },
    { field: 'NetAURLW', headerName: 'Net AUR LW' },
    { field: 'NetAURFourWeekAvg', headerName: 'Net AUR 4W Avg' },
    { field: 'NetSalesLWUSD' },
    { field: 'NetSalesFourWeekRollingUSD', headerName: 'Net Sales 4w rolling USD' },
    { field: 'NetSalesFourWeekAvgUSD', headerName: 'Net Sales 4W Avg USD' },
    { field: 'NetSalesMTDUSD' },
    { field: 'NetSalesSTDUSD' },
    { field: 'NetAURLWUSD', headerName: 'Net AUR LW USD' },
    { field: 'NetAURFourWeekAvgUSD', headerName: 'Net AUR 4W Avg USD' },
    { field: 'DemandUnitsLW' },
    { field: 'DemandUnitsFourWeekRolling', headerName: 'Demand Units 4W rolling' },
    { field: 'DemandUnitsFourWeekAvg', headerName: 'Demand Units 4W avg' },
    { field: 'DemandUnitsThirteenWeekAvg', headerName: 'Demand Units 13W avg' },
    { field: 'DemandUnitsMTD' },
    { field: 'DemandUnitsSTD' },
    { field: 'DemandSalesLW' },
    { field: 'DemandSalesFourWeekRolling', headerName: 'Demand Sales 4W rolling' },
    { field: 'DemandSalesFourWeekAvg', headerName: 'Demand Sales 4W avg' },
    { field: 'DemandSalesMTD' },
    { field: 'DemandSalesSTD' },
    { field: 'DemandAURLW', headerName: 'Demand AUR LW' },
    { field: 'DemandAURFourWeekAvg', headerName: 'Demand AUR 4W avg' },
    { field: 'DemandSalesLWUSD' },
    { field: 'DemandSalesFourWeekRollingUSD', headerName: 'Demand Sales 4W rolling USD' },
    { field: 'DemandSalesFourWeekAvgUSD', headerName: 'Demand Sales 4W Avg USD' },
    { field: 'DemandSalesMTDUSD' },
    { field: 'DemandSalesSTDUSD' },
    { field: 'DemandAURLWUSD', headerName: 'Demand AUR LW USD' },
    { field: 'DemandAURFourWeekAvgUSD', headerName: 'Demand AUR 4W avg USD' },
    { field: 'FirstOrderDate' },
    { field: 'DaysOnSale' },
    { field: 'ApsVsPlan' }
];

export const actionSalesColumnSouthEastAsia = [
    { field: 'NetUnitsLastWeek' },
    { field: 'NetUnitsFourWkAvg', headerName: 'Net Units 4W Avg' },
    { field: 'NetUnitsFourWkRolling', headerName: 'Net Units 4W rolling' },
    { field: 'NetUnitsThirteenWkAvg', headerName: 'Net Units 13W Avg' },
    { field: 'NetUnitsMTD' },
    { field: 'NetUnitsSTD' },
    { field: 'NetSalesLWUSD' },
    { field: 'NetSalesFourWeekRollingUSD', headerName: 'Net Sales 4w rolling USD' },
    { field: 'NetSalesFourWeekAvgUSD', headerName: 'Net Sales 4W Avg USD' },
    { field: 'NetSalesMTDUSD' },
    { field: 'NetSalesSTDUSD' },
    { field: 'NetAURLWUSD', headerName: 'Net AUR LW USD' },
    { field: 'NetAURFourWeekAvgUSD', headerName: 'Net AUR 4W Avg USD' },
    { field: 'DemandUnitsLW' },
    { field: 'DemandUnitsFourWeekRolling', headerName: 'Demand Units 4W rolling' },
    { field: 'DemandUnitsFourWeekAvg', headerName: 'Demand Units 4W avg' },
    { field: 'DemandUnitsThirteenWeekAvg', headerName: 'Demand Units 13W avg' },
    { field: 'DemandUnitsMTD' },
    { field: 'DemandUnitsSTD' },
    { field: 'DemandSalesLWUSD' },
    { field: 'DemandSalesFourWeekRollingUSD', headerName: 'Demand Sales 4W rolling USD' },
    { field: 'DemandSalesFourWeekAvgUSD', headerName: 'Demand Sales 4W Avg USD' },
    { field: 'DemandSalesMTDUSD' },
    { field: 'DemandSalesSTDUSD' },
    { field: 'DemandAURLWUSD', headerName: 'Demand AUR LW USD' },
    { field: 'DemandAURFourWeekAvgUSD', headerName: 'Demand AUR 4W avg USD' },
    { field: 'FirstOrderDate' },
    { field: 'DaysOnSale' },
    { field: 'ApsVsPlan' }
];